### ISSUE TITLE
Routing loader should implement the Symfony interface

### ISSUE THREAD

**Issue by stof** [umpirsky/UmpirskyI18nRoutingBundle#19]
Currently, the I18nRouteLoader is implementing its own interface, with the same signature that the Symfony one (plus an explicit return type).
As the Symfony router receives the container to load the loader, things are working as there is no typehint to validate the type of the loader. But this could break in the future if Symfony refactors the way it lazy-loads the route loader.

The class should implement the Symfony interface instead.

**Comment by stof** [comment]
On a side note, the constructor should typehint the interface too, not the DelegatingLoader implementation.

**Comment by kbond** [comment]
So it should extend `Symfony\Component\Config\Loader\Loader`?

**Comment by stof** [comment]
it should at least implement the interface
