### ISSUE TITLE
The special prefix_except_default router should use composition instead of inheritance

### ISSUE THREAD

**Issue by stof** [umpirsky/UmpirskyI18nRoutingBundle#20]
The custom router current uses inheritance, but it only wraps public methods. This means that it could totally be implemented using composition instead.

This would even simplify things, by avoiding to maintain the dependencies of the parent router in your constructor, and having to mix your own options with the Symfony ones.

**Comment by stof** [comment]
btw, BeSimpleI18nRoutingBundle already uses composition there (except that it is missing support for WarmableInterface, which is a bad news as it means that the router is not generated during `cache:warmup` but on first request)

**Comment by kbond** [comment]
@stof, does #23 do what you are suggesting? Does it support the `WarmableInterface` correctly?

**Comment by stof** [comment]
@kbond yes it does (the key is to implement the Warmable interface and to proxy the call when appropriate)
