### ISSUE TITLE
Most of the functionality of this bundle is available in core as of 4.1

### ISSUE THREAD

**Issue by kbond** [umpirsky/UmpirskyI18nRoutingBundle#28]
I opened a PR for the Symfony docs to show how to prefix all your routes with a locale: https://github.com/symfony/symfony-docs/pull/9862

With the routing improvements in 4.1, the performance benefits of this bundle over JMS (or how Symfony core handles i18n routing) is no longer relevant (I haven't done any benchmarks though) - it may even be slightly slower using a `_locale` route parameter...

I think the only thing you can't do in core is disable i18n routing on a route-by-route basis. This can effectively be accomplished by strategically importing your routes (one import for i18n and one for non-i18n)

Not sure what we want to do here with regards to this bundle but just wanted to open this as an FYI.

**Comment by umpirsky** [comment]
Yes, I know. What a great time to be a Symfony user. :)

We can keep the bundle for users that are on old version, and just add a note in readme.

**Comment by kbond** [comment]
Sounds good!

**Comment by umpirsky** [comment]
Just reading https://symfony.com/blog/new-in-symfony-4-1-internationalized-routing:

> Internally Symfony creates one route per locale (called contact.en and contact.nl in this example)

It still suffers from the same issue JMSI18nRoutingBundle does - explosion of routes. Number of routes times number of locales. Still not suitable for website with lots of languages.

**Comment by kbond** [comment]
Ok, so there is still a valid need for this bundle in 4.1+. I'll close this out.
