### ISSUE TITLE
[prefix_except_default] route order

### ISSUE THREAD

**Issue by kbond** [umpirsky/UmpirskyI18nRoutingBundle#5]
Regarding #4 

In the jms bundle, the route order is determined by the array of locales in the config - `['en', 'fr']` would cause the `en` to comes first but `['fr', 'en']` would cause the `fr` to come first. Maybe you could base it on the order as well?

**Comment by umpirsky** [comment]
Here we have only 2 routes, no matter how many locales:

```yaml
route999                        ANY      ANY      ANY    /route999                                    
route999_i18n                   ANY      ANY      ANY    /{_locale}/route999
```

Need to think if there are any cons of putting i18n route first.

**Comment by kbond** [comment]
Ah, yeah - I keep forgetting that difference.

My problem might be an edge case - I could fix it with what you suggested in #4.

**Comment by umpirsky** [comment]
OK, closing for now. Thanks.

**Comment by kbond** [comment]
I just want to point out that I don't think there are any cons to having the i18n route first - it is a more specific version of the non-i18n route so IMO it should come first.
