### ISSUE TITLE
[prefix_except_default] switch locale

### ISSUE THREAD

**Issue by kbond** [umpirsky/UmpirskyI18nRoutingBundle#8]
(I'm not sure if this is on of the things you are still working on in #4 )

When switching locale from default, I use the following code `{{ path('my_route', { _locale: 'fr' }) }}` - this generates `/my-route?_locale=fr` but should generate `/fr/my-route`. I could fix this with `{{ path('my_route_i18n', { _locale: 'fr' }) }}` but I don't think the user should have to be aware of the existence of the `*_i18n` routes.

**Comment by umpirsky** [comment]
Yes, working on it in #4 ;)

**Comment by kbond** [comment]
I thought as much :)

**Comment by kbond** [comment]
This works as expected now.
